name: release-github
run-name: ${{ github.actor }} is releasing to github

on: [workflow_dispatch]

jobs:
  build:
    if: ${{ github.ref == 'refs/heads/dev' ||  github.ref == 'refs/heads/main' }}
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: butr/actions-common-setup@v2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: >-
          mkdir Bannerlord;
          dotnet build Tweaks.Release/Tweaks.Release.csproj --configuration Publish_Release -p:GameFolder="$PWD/Bannerlord";
        shell: pwsh
        
      - name: Print Dir
        run: ls -R
        shell: pwsh
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Bannerlord
          path: ./Bannerlord/
    
  publish:
    name: Release on GitHub
    needs: ["build"]
    uses: BUTR/workflows/.github/workflows/release-github.yml@master
    with:
      mod_id: KaosesTweaks
      mod_version: ${{ needs.build-module.outputs.mod_version }}
      mod_description: ${{ needs.build-module.outputs.mod_description }}
      artifact_name: Bannerlord